artifacts_root: 'artifacts'

data_ingestion:
    data_root_dir: 'artifacts/data_ingestion'
    roboflow_api_key_file: 'roboflow_api_key.yaml'
    roboflow_workspace: 'sri-vnhii'
    roboflow_project: 'hard-hat-sample-uurjf'
    roboflow_version: '1'
    roboflow_export_format: 'yolov5'

data_validation:
    # paths
    data_root_dir: 'artifacts/data_validation'
    # inputs
    data_dir: 'artifacts/data_ingestion'
    # outputs
    STATUS_FILE: 'artifacts/data_validation/status.txt'
    # folders
    TRAIN_DIR: 'train'
    VAL_DIR: 'valid'
    TEST_DIR: 'test'
    IMG_DIR: 'images'
    LABEL_DIR: 'labels'
    LABELS_FILE_EXT: '.txt'
    # files
    DATA_FILE: 'data.yaml'

data_transformation:
    # paths
    data_root_dir: 'artifacts/data_transformation'
    # inputs
    data_dir: 'artifacts/data_ingestion'
    # outputs
    # folders
    TRAIN_DIR: 'train'
    VAL_DIR: 'valid'
    TEST_DIR: 'test'
    IMG_DIR: 'images'
    LABEL_DIR: 'labels'
    IMG_FILE_EXT: '.jpg'
    LABELS_FILE_EXT: '.txt'

model_trainer:
    # paths
    data_root_dir: 'artifacts/model_trainer'
    # inputs
    data_dir: 'artifacts/data_transformation'
    input_yaml_path: 'artifacts/data_ingestion/data.yaml'
    # outputs
    output_yaml_path: 'artifacts/model_trainer/dataset.yaml'
    # folders
    TRAIN_DIR: 'images/train'
    VAL_DIR: 'images/valid'
    TEST_DIR: 'images/test'
    # model
    model_root_path: 'yolov5'
    used_model_name: 'yolov5'
    weight_name: 'yolov5s.pt'
    no_epochs: 1
    batch_size: 16

model_evaluation:
    # paths
    data_root_dir: 'artifacts/model_evaluation'
    # inputs
    data_dir: 'artifacts/data_transformation'
    input_yaml_path: 'artifacts/model_trainer/dataset.yaml'
    # weights
    weights_path: 'artifacts/model_trainer/results/weights/best.pt'
    # model
    model_root_path: 'yolov5'
    used_model_name: 'yolov5'
    batch_size: 16